### ISSUE TITLE
On-Demand recognition is ONLY marked unavailable in the recognition dialog

### ISSUE THREAD

**Issue by ralph950412** [KieronQuinn/AmbientMusicMod#174] opened 2023-04-19 08:36 UTC
As the title described, On-Demand is marked unavailable in the recognition dialog, but not in the settings; it should've been notified in the latter one in the first place.

Below is what I see in the settings.

![Screenshot_20230419-163201](https://user-images.githubusercontent.com/88758544/233017770-585f4bd2-0506-4aa6-a7e0-bb7f36dde285.png)

**Comment by ralph950412** [comment] 2023-04-19 08:39
Meanwhile, this is what's shown in the recognition dialog.

![Screenshot_20230419-163713](https://user-images.githubusercontent.com/88758544/233018692-3695a1cb-d98e-4e83-bc63-a541cbf914bc.png)

**Comment by KieronQuinn** [comment] 2023-04-19 09:41
This isn't a new issue, it's been raised before and seems to happen only on some specific devices. I'll probably see if I can update my OP7TP to the dreaded Oxygen OS 12 build temporarily to see if that can trigger it.

**Comment by ralph950412** [comment] 2023-04-19 10:29
> This isn't a new issue, it's been raised before and seems to happen only on some specific devices. I'll probably see if I can update my OP7TP to the dreaded Oxygen OS 12 build temporarily to see if that can trigger it.

I see... Looking forward to it!
Although in my case it's just one specific custom ROM I built recently...

**Comment by KieronQuinn** [comment] 2023-04-19 22:00
Installed Oxygen 12 on it, works fine with both Shizuku as root and Sui. What device and ROM is this and are you using Shizuku as root or Sui?

**Comment by ralph950412** [comment] 2023-04-20 00:49
I use Shizuku as root, and the device is a Mi 11. ROM info: 
![Screenshot_20230420-082436](https://user-images.githubusercontent.com/88758544/233229090-0fb057c5-541a-41d7-a5be-75341ac75053.png)
(P.S. The Google app seems to have the split_sound_search_fingerprinter_split.apk)

**Comment by KieronQuinn** [comment] 2023-04-20 00:50
Can you try with [Sui](https://github.com/RikkaApps/Sui) maybe? It should behave the same, but it would be interesting to know if it does not.

**Comment by KieronQuinn** [comment] 2023-04-20 01:25
You can also try this build (zipped), it may fix it. If you still see a service error, then the issue is genuine and can't be resolved. 

[app-release.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/11278918/app-release.zip)

**Comment by ralph950412** [comment] 2023-04-20 01:28
> Can you try with [Sui](https://github.com/RikkaApps/Sui) maybe? It should behave the same, but it would be interesting to know if it does not.

What the... It's working with SUI! I wonder why Shizuku didn't work..
![Screenshot_20230420-092635](https://user-images.githubusercontent.com/88758544/233234263-36dc183c-18f3-4a08-bc9f-16b1d5997a05.png)

**Comment by KieronQuinn** [comment] 2023-04-20 01:28
Ok, could you try reverting to Shizuku (sorry!) and that build? I want to make it as compatible as possible ideally.

**Comment by ralph950412** [comment] 2023-04-20 01:35
> Ok, could you try reverting to Shizuku (sorry!) and that build? I want to make it as compatible as possible ideally.

Sure 👍

**Comment by ralph950412** [comment] 2023-04-20 01:39
> You can also try this build (zipped), it may fix it. If you still see a service error, then the issue is genuine and can't be resolved.
> 
> [app-release.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/11278918/app-release.zip)

Sorry for the late reply, but this works with both Shizuku and Sui!

**Comment by KieronQuinn** [comment] 2023-04-20 01:42
Excellent, thanks. Only detriment of the change I made is it would throw an error even later if there's a genuine problem (which should be very rare with it), so I'll get that in a release soon. 

Thanks again for your help!

**Comment by ralph950412** [comment] 2023-04-20 01:49
> Excellent, thanks. Only detriment of the change I made is it would throw an error even later if there's a genuine problem (which should be very rare with it), so I'll get that in a release soon.
> 
> Thanks again for your help!

No problem, thanks :)

**Comment by ralph950412** [comment] 2023-04-20 02:13
> > You can also try this build (zipped), it may fix it. If you still see a service error, then the issue is genuine and can't be resolved.
> > [app-release.zip](https://github.com/KieronQuinn/AmbientMusicMod/files/11278918/app-release.zip)
> 
> Sorry for the late reply, but this works with both Shizuku and Sui!

Update: Using the Shizuku method sometimes reports service error, just like what you've said

**Comment by KieronQuinn** [comment] 2023-04-20 20:21
Fixed in 2.2.2

**Closed by KieronQuinn** 2023-04-20 20:21 UTC

**Comment by TonDar0n** [comment] 2023-08-11 15:05
@KieronQuinn I'm experiencing the same issue on version 2.3.1 of the app. I'm using Shizuku on a device that is not rooted

**Comment by KieronQuinn** [comment] 2023-08-11 15:37
> @KieronQuinn I'm experiencing the same issue on version 2.3.1 of the app. I'm using Shizuku on a device that is not rooted

This is the intended behaviour as stated above. The original setup worked around this but introduced this issue, the workaround has the side effect of what you are describing.
