### ISSUE TITLE
can't get the right pixel ambient services app

### ISSUE THREAD

**Issue by fenglipop29** [KieronQuinn/AmbientMusicMod#35] opened 2021-12-30 09:50 UTC
So my phone is oneplus 7t pro, and I don't have pixel ambient services app in stock. So I tried different version of this from apkmirror, but still cannot get the right one. I tried the oldest version which is 1.0.17, but still when I click "lauch ambient music app" button I got the mod app shut down immediatly, and it says that pixel ambient services version is not right. I try click "test recognition" and it fail to start.

**Comment by KieronQuinn** [comment] 2021-12-30 11:49
You don't need to install Ambient Services, the module does that for you. It has to be a system app and a specific version, hence why you're seeing crashes.

Probably a duplicate of #33, follow the steps on there.

**Comment by fenglipop29** [comment] 2021-12-30 13:06
Tried overlayfix module in Magisk, can succesfully click "launch Ambient music App". However when I try "test recognition", it still says ambient music failed to start. Not sure why.

**Comment by KieronQuinn** [comment] 2021-12-30 13:27
Overlay fix is working then. Post a log dump.

**Comment by fenglipop29** [comment] 2021-12-30 13:58
not sure if I did this right with this logcat.
https://drive.google.com/file/d/1fBPKnePNUG-KSfsjbPQTo-QxU_vA7-IU/view?usp=sharing

**Comment by KieronQuinn** [comment] 2021-12-30 14:48
There's no error that I can see in that, but the logcat isn't a log dump, please read the FAQ for instructions of making a proper dump.

**Comment by fenglipop29** [comment] 2021-12-31 14:16
https://drive.google.com/file/d/1xKxlweWA7PH5kPdJkuv_Q7bDiKeNHFmm/view?usp=sharing
If I did this right.

**Comment by KieronQuinn** [comment] 2021-12-31 15:05
The Pixel Ambient Services log is completely empty, suggesting it hasn't been started. Try starting it by using the button in Ambient Music Mod, then do a recognition. If it's still not working, do another log dump after doing all that.

**Comment by fenglipop29** [comment] 2021-12-31 15:15
I did that.
https://drive.google.com/file/d/1AMiGBgHbeDJTt3SLp8gQTe_tGj0RebjT/view?usp=sharing

**Comment by KieronQuinn** [comment] 2021-12-31 15:32
There's still no errors in there, so I can't help any more, sorry

**Comment by kdschopra** [comment] 2022-03-20 11:09
@KieronQuinn @fenglipop29 
If you facing issue regarding Pixel Ambient Services App and your phone doesn't have that app in stock then you can get app by following this instructions
1. Uninstall Pixel Ambient Services App (If you have any another unspotted version)
2. Open Ambient Music Mod App > Go to "Installer" tab > Click on "Build Installer" > and save "ambient_music_mod_v.x.x.x.zip"
3. Locate and Open "ambient_music_mod_v.x.x.x.zip" with the help of File Manager
4. Then you can find "Pixel Ambient Services.apk" in "ambient_music_mod_v.x.x.x.zip/system/product/priv-app/com.google.intelligence.sense/com.google.intelligence.sense.apk"
5. Install it and Have A Fun.
6. Make sure you turn off auto updates in Play Store

Done

**Comment by KieronQuinn** [comment] 2022-06-19 17:55
No longer a problem with 2.0 :)

**Closed by KieronQuinn** 2022-06-19 17:55 UTC
