### ISSUE TITLE
Data base is successfully updated.But still showing downloading database 

### ISSUE THREAD

**Issue by fovvsandrew** [KieronQuinn/AmbientMusicMod#103] opened 2022-08-11 04:59 UTC
Heya.I installed Ambient music mod yesterday night and leave it to download.and the morning I realized it was completed.
![Screenshot_20220811-102101_Ambient Music Mod](https://user-images.githubusercontent.com/110643797/184067214-be939f1b-6697-4037-8a4c-3529a433d2e0.png)
As u see databases are updated.but still shows this.
![Screenshot_20220811-102113_Ambient Music Mod](https://user-images.githubusercontent.com/110643797/184067271-74b7046f-4f83-4850-bfbf-3d2f533621fb.png)
I'm using android 12 a64 bgN gsi.Anyway to fix this sir?

Thanks for your amazing work.

**Comment by KieronQuinn** [comment] 2022-08-11 09:24
16,000 is not completed, that's just the base database. 

Duplicate of #57

**Closed by KieronQuinn** 2022-08-11 09:24 UTC
