### ISSUE TITLE
Database downloading error despite download finished 

### ISSUE THREAD

**Issue by peetereczek** [KieronQuinn/AmbientMusicMod#65] opened 2022-06-22 16:05 UTC
I see that pending database downloading error is still visible despite it's already downloaded and service is working as expected

Samsung Galaxy S22 Ultra (Exynos), OEM firmware with Shizuku

https://user-images.githubusercontent.com/42431204/175079391-951a19b3-fc62-4899-96ac-0a52a511d189.mp4

**Comment by KieronQuinn** [comment] 2022-06-22 17:27
The database has not downloaded, or it would show the number of tracks on the Updates tab. You are running on the core database only.

Duplicate of #57

**Closed by KieronQuinn** 2022-06-22 17:27 UTC

**Comment by peetereczek** [comment] 2022-06-23 18:32
Just to document how it should look

![Screenshot_20220623-203142_Ambient Music Mod.png](https://user-images.githubusercontent.com/42431204/175370023-7a156e58-e805-41b7-8ca2-8fc39c506cbc.png)

**Comment by KieronQuinn** [comment] 2022-06-23 18:42
Yep, that's how it looks when it's downloaded. For future reference and advice, what made it finally download for you?

**Comment by peetereczek** [comment] 2022-06-24 11:15
Just some time with Wi-Fi and charger, as I set that database should be updated under those conditions.
On my S22 Ultra (stock) downloading was rather slow, but on Tab S5e (rooted Lineage OS 19.1) very rapid. Must have been depended on network state
